"""Draw the FireRed-styled login plate.

    python3 tools/build_firered_splash.py

Writes mods/vanbobby-firered-theme/firered/res/bg.png, which gfx.xml binds as
"background-image" and main-widgets.xml draws as logingui > logo.

WHY A PLATE AND NOT A TITLE SCREEN
The login screen exposes exactly one image to a theme. There is no widget for
the full-screen backdrop; the checkerboard and the 3D model belong to the client
and to the pokemmo3d mod. So the FireRed title composition lands as a banner
where the POKEMMO wordmark normally sits.

bg.png is declared xywh="*", a whole image with no slice geometry, so this is
the one atlas that may legitimately change size.

WHY THE LETTERING IS DRAWN HERE
The wordmark is original work in FireRed's style: a 5x7 pixel alphabet scaled
up, gold face, navy outline, hard shadow. Nintendo's Pokemon wordmark is not
traced and the Charizard is not reused. The client is PokeMMO, so the plate says
PokeMMO.

LAYOUT
Measured off PokemonFireRedRef/001/splash-login.jpg, which is the real thing at
its native 240x160. Band heights are taken as PERCENTAGES of that and scaled, so
the proportions survive whatever size the plate is drawn at:

    orange rule   5.6%     #E05400
    black        13.1%
    teal field   45.0%     #38A88C, scanlined
    flame row     4.4%     #E0E0A8 over the teal
    black        23.8%
    dark red      6.2%     #700000

Drawn at 3x, 720x480, which is also the largest the login plate can usefully be:
bg.png is xywh="*" and the logo widget sizes itself to the image, so a bigger
plate covers more of the client's 3D backdrop. That backdrop is not reachable
from a theme at all, so covering it is the only lever there is.
"""
import argparse
import os

from PIL import Image, ImageDraw, ImageFilter, ImageSequence

GIF = os.path.join(os.path.dirname(os.path.dirname(os.path.abspath(__file__))),
                   "..", "PokemonFireRedRef", "splash-charizard.gif")
XML_OUT = os.path.join(os.path.dirname(os.path.dirname(os.path.abspath(__file__))),
                       "mods", "vanbobby-firered-theme", "firered", "overrides.xml")

ANIM_XML = """<?xml version="1.0" encoding="UTF-8"?>
<!--
  Generated by tools/build_firered_splash.py. Do not hand edit.

  The login plate as a %d frame loop at %dms, which is the Charizard idle from
  PokemonFireRedRef/splash-charizard.gif composited onto the plate.

  It has to be the WHOLE plate, not just the Charizard. The login screen exposes
  exactly one image, logingui > logo bound to "background-image", so anything
  that moves has to move as part of that image.

  "background-image" is an <animation> here rather than an <area>. TWL treats an
  animation as a named image like any other, and timeSource="enabled" runs it
  continuously, which is how the client animates its chat indicators. Proven on
  a three frame spike before any of this art existed.

  The bg-frame-NN areas are internal: nothing outside this file references them,
  and the name widgets actually bind to is still "background-image".
-->
<themes>
    <images file="res/bg.png" filter="nearest">
%s
        <animation name="background-image" timeSource="enabled">
%s
        </animation>
    </images>
</themes>
"""

REPO = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
OUT = os.path.join(REPO, "mods", "vanbobby-firered-theme", "firered", "res", "bg.png")

ORANGE   = (0xF0, 0x48, 0x00)
BLACK    = (0x18, 0x18, 0x18)
TEAL     = (0x30, 0xA8, 0x90)
TEAL_DK  = (0x28, 0x90, 0x7C)
FLAME    = (0xF0, 0xC0, 0x30)
FLAME_LT = (0xF0, 0xF0, 0xA8)
DARKRED  = (0x78, 0x00, 0x00)
GOLD     = (0xF8, 0xD0, 0x30)
GOLD_DK  = (0xC8, 0x90, 0x10)
NAVY     = (0x28, 0x30, 0x68)
WHITE    = (0xF8, 0xF8, 0xF8)
SHADOW   = (0x28, 0x30, 0x30)

# A 5x7 alphabet, drawn for this plate. Rows are read left to right, MSB first.
GLYPHS = {
    "A": ["01110", "10001", "10001", "11111", "10001", "10001", "10001"],
    "C": ["01110", "10001", "10000", "10000", "10000", "10001", "01110"],
    "D": ["11110", "10001", "10001", "10001", "10001", "10001", "11110"],
    "E": ["11111", "10000", "10000", "11110", "10000", "10000", "11111"],
    "F": ["11111", "10000", "10000", "11110", "10000", "10000", "10000"],
    "I": ["11111", "00100", "00100", "00100", "00100", "00100", "11111"],
    "K": ["10001", "10010", "10100", "11000", "10100", "10010", "10001"],
    "M": ["10001", "11011", "10101", "10101", "10001", "10001", "10001"],
    "N": ["10001", "11001", "10101", "10101", "10011", "10001", "10001"],
    "O": ["01110", "10001", "10001", "10001", "10001", "10001", "01110"],
    "P": ["11110", "10001", "10001", "11110", "10000", "10000", "10000"],
    "R": ["11110", "10001", "10001", "11110", "10100", "10010", "10001"],
    "S": ["01111", "10000", "10000", "01110", "00001", "00001", "11110"],
    "V": ["10001", "10001", "10001", "10001", "10001", "01010", "00100"],
    " ": ["00000"] * 7,
}


def glyph_mask(s, scale, spacing):
    """The string as a 1-bit mask at final pixel resolution."""
    step = 5 * scale + spacing
    w, h = max(1, len(s) * step - spacing), 7 * scale
    m = Image.new("L", (w, h), 0)
    md = ImageDraw.Draw(m)
    for ci, ch in enumerate(s):
        rows = GLYPHS.get(ch, GLYPHS[" "])
        for ry, row in enumerate(rows):
            for rx, bit in enumerate(row):
                if bit == "1":
                    px, py = ci * step + rx * scale, ry * scale
                    md.rectangle([px, py, px + scale - 1, py + scale - 1], fill=255)
    return m


def dilate(mask, r):
    return mask.filter(ImageFilter.MaxFilter(2 * r + 1))


def draw_text(im, s, x, y, scale, face, outline=None, outline_px=0,
              shadow=None, shadow_px=0, spacing=0):
    """Draw the wordmark.

    The outline is a DILATION IN PIXEL SPACE, not a square drawn around each
    scaled-up cell. Per-cell outlining is one cell thick, which on a glyph only
    five cells wide swallows the counters: the holes in O, P and R fill solid
    and the wordmark reads as a slab."""
    mask = glyph_mask(s, scale, spacing)
    pad = max(outline_px, shadow_px) + scale
    canvas = Image.new("L", (mask.width + 2 * pad, mask.height + 2 * pad), 0)
    canvas.paste(mask, (pad, pad))

    if shadow and shadow_px:
        sh = dilate(canvas, outline_px) if outline_px else canvas
        im.paste(Image.new("RGBA", canvas.size, shadow + (255,)),
                 (x - pad + shadow_px, y - pad + shadow_px), sh)
    if outline and outline_px:
        im.paste(Image.new("RGBA", canvas.size, outline + (255,)),
                 (x - pad, y - pad), dilate(canvas, outline_px))
    im.paste(Image.new("RGBA", canvas.size, face + (255,)), (x - pad, y - pad), canvas)
    return mask.width


def text_width(s, scale, spacing):
    return max(1, len(s) * (5 * scale + spacing) - spacing)


def flame_row(d, y, width, height):
    """Flames along the bottom of the teal field: widest at the base, tapering
    to a tip, with a paler inner tongue. Drawn bottom up, because a flame that
    is widest at the top reads as a row of funnels."""
    step = 28
    for x in range(0, width + step, step):
        for i in range(height):
            t = i / float(height - 1)              # 0 at the tip, 1 at the base
            half = max(0, int(t * 8))
            lean = int((1.0 - t) * 2)
            d.rectangle([x - half + lean, y + i, x + half + lean, y + i], fill=FLAME)
        for i in range(height // 2, height):
            t = (i - height // 2) / float(max(height - height // 2 - 1, 1))
            half = max(0, int(t * 4))
            d.rectangle([x - half, y + i, x + half, y + i], fill=FLAME_LT)


def key_white(im, thresh=232):
    """The GIF is rendered on solid white, not on transparency. Anything that
    bright at the edges is background; the Charizard's own highlights are inside
    the silhouette, so a flood from the border keeps them."""
    im = im.convert("RGBA")
    w, h = im.size
    px = im.load()
    stack = [(0, 0), (w - 1, 0), (0, h - 1), (w - 1, h - 1)]
    seen = set()
    while stack:
        x, y = stack.pop()
        if (x, y) in seen or not (0 <= x < w and 0 <= y < h):
            continue
        seen.add((x, y))
        r, g, b, a = px[x, y]
        if r < thresh or g < thresh or b < thresh:
            continue
        px[x, y] = (0, 0, 0, 0)
        stack += [(x + 1, y), (x - 1, y), (x, y + 1), (x, y - 1)]
    return im


def charizard_frames(count, height):
    """Evenly sampled frames of the GIF, keyed and scaled to `height`."""
    if not os.path.exists(GIF):
        return []
    src = [f.convert("RGB").copy() for f in ImageSequence.Iterator(Image.open(GIF))]
    idx = [round(i * len(src) / count) % len(src) for i in range(count)]
    out = []
    for i in idx:
        im = key_white(src[i])
        bb = im.getbbox()
        if bb:
            im = im.crop(bb)
        w = max(1, round(im.width * height / im.height))
        out.append(im.resize((w, height), Image.LANCZOS))
    return out


def plate(W, H, chari=None):
    """One frame of the login plate."""
    im = Image.new("RGBA", (W, H), TEAL + (255,))
    d = ImageDraw.Draw(im)

    def band(frac_from, frac_to):
        return int(H * frac_from), int(H * frac_to)

    # Reference proportions, with ONE deliberate change: its lower black band is
    # 24% because that is where Charizard stands. We are not reusing the
    # Charizard, so a quarter of the plate would be dead space -- and the plate
    # pushes the login window down the screen, so dead space costs twice. That
    # band is trimmed and the teal field takes the room.
    o0, o1 = band(0.000, 0.056)      # orange rule
    b0, b1 = band(0.056, 0.187)      # black
    t0, t1 = band(0.187, 0.740)      # teal field
    f0, f1 = band(0.740, 0.810)      # flame row
    k0, k1 = band(0.810, 0.920)      # black
    r0, r1 = band(0.920, 1.000)      # dark red rule

    d.rectangle([0, o0, W, o1], fill=ORANGE)
    d.rectangle([0, b0, W, b1], fill=BLACK)
    d.rectangle([0, t0, W, f1], fill=TEAL)
    for y in range(t0, f1, 2):
        d.rectangle([0, y, W, y], fill=TEAL_DK)
    flame_row(d, f0 - 6, W, (f1 - f0) + 6)
    d.rectangle([0, k0, W, k1], fill=BLACK)
    d.rectangle([0, r0, W, H], fill=DARKRED)

    # The reference puts the wordmark LEFT and Charizard RIGHT, overlapping only
    # slightly. Centring the wordmark and dropping the Charizard on top of it
    # buries both.
    scale = max(4, int(W / 70))
    spacing = int(scale * 1.2)
    title = "POKEMMO"
    tx = int(W * 0.05)
    draw_text(im, title, tx, t0 + int(H * 0.07), scale, face=GOLD,
              outline=NAVY, outline_px=max(2, scale // 3),
              shadow=SHADOW, shadow_px=max(2, scale // 3), spacing=spacing)

    s2 = max(2, scale // 3)
    sp2 = max(2, s2)
    sub = "FIRERED VERSION"
    draw_text(im, sub, tx + int(W * 0.04), t0 + int(H * 0.28), s2, face=WHITE,
              outline=SHADOW, outline_px=max(1, s2 // 2), spacing=sp2)

    if chari is not None:
        # anchored to the RIGHT edge and standing on the flame row, as the title
        # screen has it. Anchoring right also keeps a wide frame of the turn from
        # running off the plate, which centring does not.
        x = W - chari.width - int(W * 0.03)
        y = f1 - chari.height + 4
        im.alpha_composite(chari, (max(0, x), max(0, y)))
    return im


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--frames", type=int, default=20,
                    help="0 for a still plate")
    ap.add_argument("--width", type=int, default=560)
    args = ap.parse_args()

    W = args.width
    H = int(W * 384 / 720)

    chari = charizard_frames(args.frames, int(H * 0.58)) if args.frames else []
    if not chari:
        im = plate(W, H)
        os.makedirs(os.path.dirname(OUT), exist_ok=True)
        im.save(OUT)
        print("wrote %s  %dx%d (still)" % (os.path.relpath(OUT, REPO), W, H))
        return

    frames = [plate(W, H, c) for c in chari]
    cols = 4
    rows = (len(frames) + cols - 1) // cols
    atlas = Image.new("RGBA", (W * cols, H * rows), (0, 0, 0, 0))
    rects = []
    for i, f in enumerate(frames):
        x, y = (i % cols) * W, (i // cols) * H
        atlas.paste(f, (x, y))
        rects.append((x, y, W, H))
    os.makedirs(os.path.dirname(OUT), exist_ok=True)
    atlas.save(OUT)

    per = max(40, round(3930 / len(frames)))
    areas = "\n".join('        <area name="bg-frame-%02d" xywh="%d,%d,%d,%d"/>' % ((i,) + r)
                      for i, r in enumerate(rects))
    fr = "\n".join('            <frame ref="bg-frame-%02d" duration="%d"/>' % (i, per)
                    for i in range(len(rects)))
    open(XML_OUT, "w").write(ANIM_XML % (len(frames), per, areas, fr))
    print("wrote %s  %dx%d  %d frames @ %dms  (%.1f KB)"
          % (os.path.relpath(OUT, REPO), atlas.width, atlas.height,
             len(frames), per, os.path.getsize(OUT) / 1024.0))


if __name__ == "__main__":
    main()
