"""Draw the full-screen FireRed field behind the login screen.

    python3 tools/build_firered_loginbg.py

Writes firered/res/login-bg.png and firered/login-bg-firered.xml.

WHY THIS EXISTS
The client's 3D login scene looked unreachable for a long time. It is not: the
login ROOT container, `logingui`, takes a `background` param, and stock simply
never sets one, so the 3D scene shows through. PARAGON sets it in its
android.xml, which is where the trick came from. Setting it covers the backdrop
completely.

WHY IT IS A 9-SLICE AND NOT ONE STRETCHED IMAGE
A container background is stretched to the container, and the container is the
whole window. One flat image would smear the bands and the Charizard as the
window changed shape. A 3x3 grid pins the four corners at their pixel size,
stretches the middle, and tiles the edges:

    weightsX="0,1,0"   left corner | tiled middle | RIGHT CORNER
    weightsY="0,1,0"   top bands   | stretchy teal | bottom bands

The Charizard lives in the bottom-right CORNER cell, which is the only kind of
cell that never scales, so it stays crisp and anchored to the corner at any
window size. It cannot go in a tiled or stretched cell: a tiled cell would
repeat it across the screen.
"""
import argparse
import os

from PIL import Image, ImageDraw

REPO = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
MOD = os.path.join(REPO, "mods", "vanbobby-firered-theme", "firered")
PNG = os.path.join(MOD, "res", "login-bg.png")
XML = os.path.join(MOD, "login-bg-firered.xml")

ORANGE = (0xE0, 0x54, 0x00)
BLACK = (0x18, 0x18, 0x18)
TEAL = (0x30, 0xA8, 0x90)
TEAL_DK = (0x28, 0x90, 0x7C)
CLOUD = (0xF8, 0xF8, 0xD0)      # the dome body
CLOUD_E = (0xF0, 0xD8, 0x90)    # its gold edge and the dither at the base
CLOUD_HI = (0xF8, 0xF8, 0xF0)   # top left highlight
DARKRED = (0x70, 0x00, 0x00)

# Proportions from PokemonFireRedRef/001/splash-login.jpg: a thin orange rule,
# black under it, and a deep black footer above the dark red rule.
TOP = [(ORANGE, 12), (BLACK, 34)]
FOOT = [(BLACK, 76), (DARKRED, 20)]
CLOUD_H = 26
MID_H = 16                # a whole pattern tile, TILED rather than stretched
EDGE_W = 32               # one cloud's worth, tiled across
CHARI_H = 300


def field(d, x0, y0, w, h):
    """The teal ground.

    Scanlines alone read as flat at this size, so it also carries a sparse
    diagonal dither, which is how a GBC era background gets depth out of two
    tones. The pattern repeats on EDGE_W by MID_H so it survives being tiled."""
    d.rectangle([x0, y0, x0 + w - 1, y0 + h - 1], fill=TEAL)
    for y in range(y0, y0 + h, 2):
        d.rectangle([x0, y, x0 + w - 1, y], fill=TEAL_DK)
    for y in range(y0, y0 + h):
        for x in range(x0, x0 + w):
            if (x * 3 + y * 5) % 16 == 0:
                d.point((x, y), fill=TEAL_DK)
            elif (x * 3 - y * 5) % 32 == 0:
                d.point((x, y), fill=(0x38, 0xB4, 0x9C))


def clouds(d, x0, y0, w, h):
    """The row of pale domes along the top of the black footer.

    These were triangles until someone pointed at them and said "pyramids".
    Magnifying the reference settles it: rounded cloud domes with a gold edge
    and a dither of the same gold at the base, not flames and not spikes."""
    import math
    for cx in range(x0 + EDGE_W // 2, x0 + w + EDGE_W, EDGE_W):
        rx, ry = EDGE_W // 2 + 1, h - 2
        for i in range(h):
            dy = (h - 1 - i) / float(ry)          # 1 at the top, 0 at the base
            if dy > 1:
                continue
            half = int(rx * math.sqrt(max(0.0, 1.0 - dy * dy)))
            if half <= 0:
                continue
            y = y0 + i
            d.rectangle([cx - half, y, cx + half, y], fill=CLOUD)
            d.point((cx - half, y), fill=CLOUD_E)
            d.point((cx + half, y), fill=CLOUD_E)
            if i < h // 3:
                d.rectangle([cx - half + 1, y, cx - half // 2, y], fill=CLOUD_HI)
        # the gold dither that fades the dome into the black band
        for i in range(h - h // 3, h):
            for x in range(cx - rx, cx + rx + 1):
                if (x + i) % 3 == 0 and (x * 2 + i) % 5 < 2:
                    d.point((x, y0 + i), fill=CLOUD_E)


SCENE = os.path.join(os.path.dirname(os.path.dirname(os.path.abspath(__file__))),
                     "..", "PokemonFireRedRef", "login-background.png")

SCENE_XML = '''<?xml version="1.0" encoding="UTF-8"?>
<!--
  Generated by tools/build_firered_loginbg.py from a painted scene.

  Two rows, weightsY "1,0". The top row is a thin strip of flat sky and takes
  all the leftover height; the bottom row is the landscape at a fixed pixel
  height, pinned to the bottom. The horizon therefore stays put and only the
  sky grows, which is what a taller window should do. Stretching the whole
  image instead squashes the horizon on any aspect but the artwork's own.

  One column, weightsX "1", stretched across the width. The scene is a
  horizontal panorama, so it survives being somewhat wider or narrower.

  filter is "nearest" on purpose. This is pixel art; smoothing would blur the
  dithering into mud.
-->
<themes>
    <images file="res/login-bg.png" filter="nearest">
        <grid name="firered-login.background" weightsX="1" weightsY="1,0">
            <area xywh="0,0,%d,%d"/>
            <area xywh="0,%d,%d,%d"/>
        </grid>
    </images>
</themes>
'''


def from_scene(src):
    '''Build the backdrop from a painted scene instead of drawn bands.

    A scene cannot just be stretched over the window: the aspect is the user's,
    not the artwork's, and a squashed horizon reads as wrong immediately. Only
    the sky stretches here, and the landscape keeps its pixel height.

    Only a sky strip and the landscape band ship. This scene is 1536x1024 and
    its top 448 rows are flat sky that drifts by 2 over 400 rows, so carrying
    them would be most of a megabyte of one colour.
    '''
    im = Image.open(src).convert("RGBA")
    w, h = im.size

    def lightest(y):
        return max(sum(im.getpixel((x, y))[:3]) / 3 for x in range(0, w, 5))

    horizon = 0
    for y in range(0, h, 8):
        if lightest(y) > 180:
            horizon = max(0, y - 16)
            break
    if not horizon:
        horizon = h // 3

    strip_h = 8
    band = im.crop((0, horizon, w, h))
    out = Image.new("RGBA", (w, strip_h + band.height))
    out.paste(im.crop((0, 0, w, strip_h)), (0, 0))
    out.paste(band, (0, strip_h))
    out.save(PNG)
    open(XML, "w").write(SCENE_XML % (w, strip_h, strip_h, w, band.height))
    print("login-bg.png %dx%d from scene: sky strip %d, landscape %d  (%.0f KB)"
          % (out.width, out.height, strip_h, band.height,
             os.path.getsize(PNG) / 1024.0))


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--scene", nargs="?", const=SCENE, default=None,
                    help="build from a painted scene instead of drawn bands")
    args = ap.parse_args()
    if args.scene:
        if not os.path.exists(args.scene):
            raise SystemExit("no such scene: %s" % args.scene)
        return from_scene(args.scene)
    import importlib.util
    spec = importlib.util.spec_from_file_location(
        "sp", os.path.join(os.path.dirname(os.path.abspath(__file__)),
                           "build_firered_splash.py"))
    sp = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(sp)
    chari = None   # the Charizard is centred and animated, so it lives in the
                   # logo widget, not here. See the note above main().

    top_h = sum(h for _, h in TOP)
    foot_h = sum(h for _, h in FOOT)
    bot_h = CLOUD_H + foot_h
    corner_w = EDGE_W

    W = EDGE_W + EDGE_W + corner_w
    H = top_h + MID_H + bot_h
    im = Image.new("RGBA", (W, H), TEAL + (255,))
    d = ImageDraw.Draw(im)

    # top row: the rules, full width
    y = 0
    for c, h in TOP:
        d.rectangle([0, y, W, y + h - 1], fill=c)
        y += h
    # middle row: the one stretchable slice
    field(d, 0, y, W, MID_H)
    y += MID_H
    # bottom row: teal, then flames, then the footer rules
    bot0 = y
    field(d, 0, bot0, W, bot_h)
    clouds(d, 0, bot0 + bot_h - foot_h - CLOUD_H, W, CLOUD_H)
    y = bot0 + bot_h - foot_h
    for c, h in FOOT:
        d.rectangle([0, y, W, y + h - 1], fill=c)
        y += h

    os.makedirs(os.path.dirname(PNG), exist_ok=True)
    im.save(PNG)

    cols = [(0, EDGE_W), (EDGE_W, EDGE_W), (EDGE_W * 2, corner_w)]
    rows = [(0, top_h), (top_h, MID_H), (bot0, bot_h)]
    areas = []
    for ry, (ry0, rh) in enumerate(rows):
        for cx, (cx0, cw) in enumerate(cols):
            # only the middle COLUMN tiles; the corner column carries the
            # Charizard and must never repeat
            # The middle ROW is tiled too, not stretched. Stretching a 2px
            # scanline pair over hundreds of pixels turns the stripes into two
            # enormous bands, which is exactly what the first attempt did.
            tiled = ' tiled="true"' if (cx == 1 or ry == 1) else ""
            areas.append('            <area xywh="%d,%d,%d,%d"%s/>'
                         % (cx0, ry0, cw, rh, tiled))
    open(XML, "w").write('''<?xml version="1.0" encoding="UTF-8"?>
<!--
  Generated by tools/build_firered_loginbg.py. Do not hand edit.

  The FireRed field behind the WHOLE login screen, set as the background of the
  logingui container. Stock leaves that param unset, which is the only reason
  the client's 3D scene is visible at all.

  A 3x3 grid, weightsX and weightsY both "0,1,0". Corners keep their pixel size;
  the middle column and the middle row both TILE rather than stretch, because
  the field is scanlined and stretching a 2px stripe pair over half a screen
  turns it into two huge bands.

  No Charizard here. It has to be centred and animated, and this grid can offer
  neither: a corner cell cannot centre, and the centre cell tiles, which would
  march copies of it across the screen. It lives in the logo widget instead,
  which is already centred and already animates.
-->
<themes>
    <images file="res/login-bg.png" filter="nearest">
        <grid name="firered-login.background" weightsX="0,1,0" weightsY="0,1,0">
%s
        </grid>
    </images>
</themes>
''' % "\n".join(areas))
    print("login-bg.png %dx%d  cols %s  rows %s  charizard %s"
          % (W, H, [c[1] for c in cols], [r[1] for r in rows],
             "%dx%d" % chari.size if chari else "none"))


if __name__ == "__main__":
    main()
