#!/usr/bin/env python3
"""Test SEVERAL candidate theme paths per screenshot instead of one.

    tools/probe_paths.py --set "battlegui>label,battle-frame>label,battlegui>spritelabel"
    tools/probe_paths.py --clear

Which widget the client creates, and what it names it, is the one question
neither theme_lint.py nor preview_firered.py can answer: it is decided by
PokeMMO's own code at runtime. The only instrument is the game, and the only
reader is the user, so the cost of an answer is one login and one screenshot.

That cost is fixed. What is NOT fixed is how many candidates a single screenshot
settles. Painting each candidate a DIFFERENT loud colour turns one screenshot
into N answers: whichever colour appears names the live path, and the ones that
do not appear are eliminated. Six candidates cost the same as one.

Writes into widgets-firered.xml between markers, so --clear takes it all back
out and the file returns to exactly what it was.
"""
import argparse
import os
import re
import sys

REPO = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
WIDGETS = os.path.join(REPO, "mods", "vanbobby-firered-theme",
                       "firered", "widgets-firered.xml")
BEGIN = "    <!-- PROBE-BEGIN: generated by tools/probe_paths.py -->"
END = "    <!-- PROBE-END -->"

# Backgrounds no two of which can be mistaken for each other on a screenshot.
# All exist in the stock tree, so none of them needs new art.
PAINTS = [
    ("RED",      "ui-frame-red.background"),
    ("GREEN",    "ui-frame-green.background"),
    ("NAVY",     "ui-inner-frame-inverted.background"),
    ("LAVENDER", "ui-popup.background"),
    ("BLUE",     "ui-box.selected"),
    ("GOLD",     "mi-label-title"),
]


def block(paths):
    # A double hyphen is illegal inside an XML comment and makes the whole file
    # unparseable. This generator writes comments, so it checks its own output:
    # the mistake has been made four times by hand in this repo already.
    out = [BEGIN,
           "    <!-- TEMPORARY. Each candidate below is painted a different",
           "         colour; whichever one shows up in game is the live path.",
           "         Take it back out with probe_paths.py, clear flag. -->"]
    for i, path in enumerate(paths):
        colour, image = PAINTS[i % len(PAINTS)]
        parts = [p.strip() for p in path.split(">") if p.strip()]
        pad = "    "
        out.append("%s<!-- %s = %s -->" % (pad, colour, " > ".join(parts)))
        for d, name in enumerate(parts):
            out.append('%s<theme name="%s"%s>'
                       % (pad + "    " * d, name,
                          ' ref="-defaults" allowWildcard="true"'
                          if d == len(parts) - 1 else ""))
        inner = pad + "    " * len(parts)
        out.append('%s<param name="background"><image>%s</image></param>'
                   % (inner, image))
        for d in range(len(parts) - 1, -1, -1):
            out.append("%s</theme>" % (pad + "    " * d))
    out.append(END)
    text = "\n".join(out) + "\n"
    for line in text.splitlines():
        if "--" in line and not line.strip().startswith("<!--") \
                and not line.strip().endswith("-->"):
            raise SystemExit("probe would emit an illegal XML comment: " + line)
    for line in text.splitlines():
        body = line.strip()
        if body.startswith("<!--") and "--" in body[4:-3]:
            raise SystemExit("probe would emit an illegal XML comment: " + line)
    return text


def strip(text):
    return re.sub(re.escape(BEGIN) + r".*?" + re.escape(END) + r"\n",
                  "", text, flags=re.S)


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--set", metavar="PATHS",
                    help="comma separated, each like parent>child>leaf")
    ap.add_argument("--clear", action="store_true")
    a = ap.parse_args()
    text = strip(open(WIDGETS).read())

    if a.clear:
        open(WIDGETS, "w").write(text)
        print("probe removed; widgets-firered.xml is back to normal")
        return
    if not a.set:
        sys.exit("nothing to do: pass --set or --clear")

    paths = [p for p in (x.strip() for x in a.set.split(",")) if p]
    if len(paths) > len(PAINTS):
        sys.exit("at most %d candidates: more colours than that stop being "
                 "distinguishable on a screenshot" % len(PAINTS))
    text = text.replace("</themes>", block(paths) + "</themes>")
    open(WIDGETS, "w").write(text)
    print("probing %d path(s). Build, log in, screenshot the screen in "
          "question:\n" % len(paths))
    for i, path in enumerate(paths):
        print("   %-9s %s" % (PAINTS[i % len(PAINTS)][0], path))
    print("\nWhichever colour appears is the live path. Colours that do not "
          "appear are eliminated.\nThen: tools/probe_paths.py --clear")


if __name__ == "__main__":
    main()
